module.exports = [
    'Assertion Testing',
    'Async Hooks',
    'Buffer',
    'C++ Addons',
    'C/C++ Addons - N-API',
    'Child Processes',
    'Cluster',
    'Command Line Options',
    'Console',
    'Crypto',
    'Debugger',
    'Deprecated APIs',
    'DNS',
    'Domain',
    'ECMAScript Modules',
    'Errors',
    'Events',
    'File System',
    'Globals',
    'HTTP',
    'HTTP/2',
    'HTTPS',
    'Inspector',
    'Internationalization',
    'Modules',
    'Net',
    'OS',
    'Path',
    'Performance Hooks',
    'Process',
    'Punycode',
    'Query Strings',
    'Readline',
    'REPL',
    'Stream',
    'String Decoder',
    'Timers',
    'TLS/SSL',
    'Trace Events',
    'TTY',
    'UDP/Datagram',
    'URL',
    'Utilities',
    'V8',
    'VM',
    'Worker Threads',
    'Zlib',
]