module.exports = [
    'Assertion testing',
    'Async hooks',
    'Buffer',
    'C++ Addons',
    'C/C++ Addons with N-API',
    'C++ Embedder API',
    'Child Processes',
    'Cluster',
    'Command line options',
    'Console',
    'Crypto',
    'Debugger',
    'Deprecated APIs',
    'DNS',
    'Domain',
    'Errors',
    'Events',
    'File system',
    'Globals',
    'HTTP',
    'HTTP/2',
    'HTTPS',
    'Inspector',
    'Internationalization',
    'Modules: CommonJS modules',
    'Modules: ECMAScript modules',
    'Modules: module API',
    'Modules: Packages',
    'Net',
    'OS',
    'Path',
    'Performance hooks',
    'Policies',
    'Process',
    'Punycode',
    'Query strings',
    'Readline',
    'REPL',
    'Report',
    'Stream',
    'String decoder',
    'Timers',
    'TLS/SSL',
    'Trace events',
    'TTY',
    'UDP/datagram',
    'URL',
    'Utilities',
    'V8',
    'VM',
    'WASI',
    'Worker threads',
    'Zlib',
]