module.exports = [
    'Assertion Testing',
    'Buffer',
    'C++ Addons',
    'C/C++ Addons - N-API',
    'Child Processes',
    'Cluster',
    'Command Line Options',
    'Console',
    'Crypto',
    'Debugger',
    'DNS',
    'Domain',
    'Errors',
    'Events',
    'File System',
    'Globals',
    'HTTP',
    'HTTPS',
    'Internationalization',
    'Modules',
    'Net',
    'OS',
    'Path',
    'Process',
    'Punycode',
    'Query Strings',
    'Readline',
    'REPL',
    'Stream',
    'String Decoder',
    'Timers',
    'TLS/SSL',
    'TTY',
    'UDP/Datagram',
    'URL',
    'Utilities',
    'V8',
    'VM',
    'ZLIB',
]